# Generated by Django 3.0.5 on 2021-04-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlmain', '0002_auto_20210424_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Number', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=50)),
                ('Discrete_Mathematics', models.CharField(max_length=2)),
                ('Engineering_Physics', models.CharField(max_length=2)),
                ('Programming_through_Cpp', models.CharField(max_length=2)),
                ('Data_Structures', models.CharField(max_length=2)),
                ('Environmental_Sciences', models.CharField(max_length=2)),
                ('Physics_Lab', models.CharField(max_length=2)),
                ('Cpp_Lab', models.CharField(max_length=2)),
                ('Data_Structures_Lab', models.CharField(max_length=2)),
                ('CGPA', models.FloatField()),
            ],
        ),
    ]
