# Generated by Django 3.0.5 on 2021-04-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlmain', '0003_cse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHEM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Number', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=50)),
                ('Engineering_Physics', models.CharField(max_length=2)),
                ('Engineering_Mathematics_II', models.CharField(max_length=2)),
                ('PDS', models.CharField(max_length=2)),
                ('Chemical_Process_Calculations', models.CharField(max_length=2)),
                ('Fluid_Mechanics', models.CharField(max_length=2)),
                ('Environmental_Sciences', models.CharField(max_length=2)),
                ('PDS_Lab', models.CharField(max_length=2)),
                ('CGPA', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CIVIL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Number', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=50)),
                ('Engineering_Physics', models.CharField(max_length=2)),
                ('Mathematical_Methods', models.CharField(max_length=2)),
                ('Basic_Electrical_and_Electronics_Engineering', models.CharField(max_length=2)),
                ('Engineering_mechanics', models.CharField(max_length=2)),
                ('Engineering_Geology', models.CharField(max_length=2)),
                ('Environmental_Studies', models.CharField(max_length=2)),
                ('Engineering_Physics_Lab', models.CharField(max_length=2)),
                ('Workshop', models.CharField(max_length=2)),
                ('CGPA', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ECE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Number', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=50)),
                ('Basic_Electronics', models.CharField(max_length=2)),
                ('Basic_Electronics_Lab', models.CharField(max_length=2)),
                ('Computational_Lab', models.CharField(max_length=2)),
                ('English_1', models.CharField(max_length=2)),
                ('Mathematical_Methods', models.CharField(max_length=2)),
                ('Network_Theory', models.CharField(max_length=2)),
                ('OOPS', models.CharField(max_length=2)),
                ('OOPS_Lab', models.CharField(max_length=2)),
                ('Signals_and_Systems', models.CharField(max_length=2)),
                ('CGPA', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MECH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Number', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=50)),
                ('Engineering_Mechanics', models.CharField(max_length=2)),
                ('Material_Science_and_Metallurgy', models.CharField(max_length=2)),
                ('Material_Science_and_Metallurgy_Lab', models.CharField(max_length=2)),
                ('Mathematical_Methods', models.CharField(max_length=2)),
                ('PDS', models.CharField(max_length=2)),
                ('PDS_Lab', models.CharField(max_length=2)),
                ('Environmental_Sciences', models.CharField(max_length=2)),
                ('CGPA', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MME',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Number', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=50)),
                ('Engineering_Chemistry', models.CharField(max_length=2)),
                ('Engineering_Chemistry_Laboratory', models.CharField(max_length=2)),
                ('Materials_Thermodynamics', models.CharField(max_length=2)),
                ('Engineering_Mathematical_2', models.CharField(max_length=2)),
                ('Metallography_Laboratory', models.CharField(max_length=2)),
                ('Physical_Metallurgy', models.CharField(max_length=2)),
                ('PDS', models.CharField(max_length=2)),
                ('PDS_Lab', models.CharField(max_length=2)),
                ('CGPA', models.FloatField()),
            ],
        ),
    ]
