# Generated by Django 3.0.5 on 2021-04-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xlmain', '0004_chem_civil_ece_mech_mme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='civil',
            old_name='Basic_Electrical_and_Electronics_Engineering',
            new_name='BEEE',
        ),
    ]
