# Generated by Django 3.0.5 on 2021-04-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xlmain', '0005_auto_20210424_0611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chem',
            old_name='Engineering_Mathematics_II',
            new_name='Engineering_Mathematics_2',
        ),
    ]
