# Generated by Django 3.0.5 on 2021-04-24 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xlmain', '0007_auto_20210424_0629'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_name',
        ),
        migrations.RenameField(
            model_name='chem',
            old_name='Name',
            new_name='Student_Name',
        ),
        migrations.RenameField(
            model_name='civil',
            old_name='Name',
            new_name='Student_Name',
        ),
        migrations.RenameField(
            model_name='cse',
            old_name='Name',
            new_name='Student_Name',
        ),
        migrations.RenameField(
            model_name='ece',
            old_name='Name',
            new_name='Student_Name',
        ),
        migrations.RenameField(
            model_name='mech',
            old_name='Name',
            new_name='Student_Name',
        ),
        migrations.RenameField(
            model_name='mme',
            old_name='Name',
            new_name='Student_Student_Name',
        ),
    ]
