# Generated by Django 3.0.5 on 2021-04-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xlmain', '0008_auto_20210424_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mme',
            old_name='Student_Student_Name',
            new_name='Student_Name',
        ),
    ]
